# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-05 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sna1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sna2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sna3',
        ),
        migrations.AddField(
            model_name='product',
            name='gpu',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='gpu_alt',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='os_alt',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='processor_alt',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='screen_size',
            field=models.FloatField(default=15.6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='customer_type',
            field=models.CharField(max_length=60),
        ),
    ]
