# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-05 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190805_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hdd',
        ),
        migrations.RemoveField(
            model_name='product',
            name='service_type',
        ),
    ]
