# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-05 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190805_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.CharField(max_length=20),
        ),
    ]
